#!/usr/bin/env bash
# Regenerates embedded_known_hosts.txt — the baked-in SSH host keys for the
# major public git hosts that cronicle verifies against out of the box.
#
# Each host's fetched key is cross-checked against its OFFICIALLY PUBLISHED
# fingerprint before it's written. If a host rotates its keys (GitHub did in
# 2023 after a private-key exposure), update the EXPECTED_FP map below from
# the host's docs and re-run. A mismatch aborts — we never embed a key we
# can't verify, because a wrong key presents to users as a MITM alert.
#
# Run:  bash internal/cronicle/gen_known_hosts.sh
set -euo pipefail

HOSTS=(github.com gitlab.com bitbucket.org ssh.dev.azure.com)

# Officially published fingerprints (SHA256, any key type). Sources:
#   github.com    — https://docs.github.com/.../githubs-ssh-key-fingerprints
#   gitlab.com    — https://docs.gitlab.com/ee/user/gitlab_com/#ssh-host-keys-fingerprints
#   bitbucket.org — https://support.atlassian.com/.../ssh-keys/
#   ssh.dev.azure.com — https://learn.microsoft.com/.../use-ssh-keys-to-authenticate
# At least one fingerprint per host must appear in the keyscan output.
EXPECTED_FP=(
  "SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU"  # github ed25519
  "SHA256:eUXGGm1YGsMAS7vkcx6JOJdOGHPem5gQp4taiCfCLB8"  # gitlab ed25519
  "SHA256:ybgmFkzwOSotHTHLJgHO0QN8L0xErw6vd0VhFA9m3SM"  # bitbucket ed25519
  "SHA256:ohD8VZEXGWo6Ez8GSEJQ9WpafgLFsOfLOtGGQCQo6Og"  # azure devops rsa
)

OUT="$(dirname "$0")/embedded_known_hosts.txt"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by gen_known_hosts.sh — do not edit by hand."
  echo "# Baked-in SSH host keys for major public git hosts. Each key was"
  echo "# fetched with ssh-keyscan and cross-checked against the host's"
  echo "# officially published fingerprint at generation time."
} > "$TMP"

for h in "${HOSTS[@]}"; do
  scan=$(ssh-keyscan -t ed25519,rsa,ecdsa "$h" 2>/dev/null)
  if [ -z "$scan" ]; then
    echo "abort: ssh-keyscan returned nothing for $h" >&2
    exit 1
  fi
  fps=$(echo "$scan" | ssh-keygen -lf - 2>/dev/null)
  matched=0
  for want in "${EXPECTED_FP[@]}"; do
    if echo "$fps" | grep -qF "$want" && echo "$fps" | grep -qiF "$h"; then
      matched=1
    fi
  done
  if [ "$matched" -ne 1 ]; then
    echo "abort: no published fingerprint matched for $h" >&2
    echo "got:" >&2
    echo "$fps" >&2
    exit 1
  fi
  echo "$scan" >> "$TMP"
done

mv "$TMP" "$OUT"
trap - EXIT
echo "wrote $OUT"
